spring:
  application:
    name: passenger
  data:
    mongodb:
      uri: mongodb+srv://nabz:nabz@workshop.rh1jm.mongodb.net/Workshop?retryWrites=true&w=majority
routes:
  api:
    base-url: http://localhost:8081
    get-by-id: /routes/{idString}

vehicles:
  api:
    base-url: http://localhost:8082
    get-by-id: /vehicles/{idString}